spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL} # gmail 계정
    password: ${APP_PASSWORD} # gmail 패스워드
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            provider: kakao
            redirect-uri: ${kakao.redirect.url}
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  issuer: test@test.com
  secret_key: ${JWT_SECRET_KEY}
  expiration: 86400000 # 1 day
  refresh-token:
    expiration: 604800000 # 7 days